### PR TITLE
implement MarkupRenderer

### LINKED ISSUE #5: Markup renderer
screen shot 2017-09-20 at 7 23 29 pm

### PR DESCRIPTION
**Pull request by R1ZZU**
Closes #5

### CODE REVIEW

**Comment by R1ZZU** [comment]
To be implemented:
- [ ] highlight nodes to select
- [ ] deal with text

**Comment by kirilknysh** [comment]
image

1. Dots are ellipses not circles
2. Do we want to make "empty" (border instead of background) dots for expected elements?

**Comment by DaQuirm** [comment]
> Do we want to make "empty" (border instead of background) dots for expected elements?
Definitely, with a sufficiently thick stroke

**Comment by R1ZZU** [comment]
> Do we want to make "empty" (border instead of background) dots for expected elements?

already implemented

screen shot 2017-09-26 at 12 39 01 pm

**Comment by R1ZZU** [comment]
> Dots are ellipses not circles

screen shot 2017-09-26 at 12 39 57 pm

**Comment by kirilknysh** [comment]
@R1ZZU , yes, and paddings/margins on top and bottom :)

**Comment by R1ZZU** [comment]
Eagle eye!

**Comment by kirilknysh** [comment]
🦅 👀

**Pull request merged**
